import "./globals.css";

import { Toaster } from "@/components/ui/sonner";
export const metadata = {
  title: "Price Deals",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en">
      <body>{children}
        <Toaster richColors/>
      </body>
    </html>
  );
}
